In [1]:
from scipy import stats

In [3]:
stats.f.a, stats.f.b

(0.0, inf)

In [6]:
stats.norm.a, stats.norm.b

(-inf, inf)

In [8]:
print('bounds of distribution lower: %s, upper: %s' % (stats.norm.a, stats.norm.b))

bounds of distribution lower: -inf, upper: inf


In [5]:
print(stats.norm.__doc__)

A normal continuous random variable.

    The location (``loc``) keyword specifies the mean.
    The scale (``scale``) keyword specifies the standard deviation.

    As an instance of the `rv_continuous` class, `norm` object inherits from it
    a collection of generic methods (see below for the full list),
    and completes them with details specific for this particular distribution.
    
    Methods
    -------
    rvs(loc=0, scale=1, size=1, random_state=None)
        Random variates.
    pdf(x, loc=0, scale=1)
        Probability density function.
    logpdf(x, loc=0, scale=1)
        Log of the probability density function.
    cdf(x, loc=0, scale=1)
        Cumulative distribution function.
    logcdf(x, loc=0, scale=1)
        Log of the cumulative distribution function.
    sf(x, loc=0, scale=1)
        Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
    logsf(x, loc=0, scale=1)
        Log of the survival function.
    ppf(q, loc=0, scale

In [11]:
rv = stats.norm()
dir(rv) 

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'a',
 'args',
 'b',
 'cdf',
 'dist',
 'entropy',
 'expect',
 'interval',
 'isf',
 'kwds',
 'logcdf',
 'logpdf',
 'logpmf',
 'logsf',
 'mean',
 'median',
 'moment',
 'pdf',
 'pmf',
 'ppf',
 'random_state',
 'rvs',
 'sf',
 'stats',
 'std',
 'support',
 'var']

In [12]:
dist_continu = [d for d in dir(stats) if isinstance(getattr(stats, d), stats.rv_continuous)]
dist_discrete = [d for d in dir(stats) if isinstance(getattr(stats, d), stats.rv_discrete)]
print('number of continuous distributions: %d' % len(dist_continu))
print('number of discrete distributions:   %d' % len(dist_discrete))

number of continuous distributions: 101
number of discrete distributions:   15


In [14]:
stats.norm.cdf([-1., 0, 1])

array([0.15865525, 0.5       , 0.84134475])

In [15]:
import numpy as np
stats.norm.cdf(np.array([-1., 0, 1]))

array([0.15865525, 0.5       , 0.84134475])

In [16]:
stats.norm.mean(), stats.norm.std(), stats.norm.var()

(0.0, 1.0, 1.0)

In [19]:
stats.norm.stats(moments="mvsk") # mean variance skew kurtosis

(array(0.), array(1.), array(0.), array(0.))

In [24]:
stats.norm.rvs(size=3, random_state=42) # random

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [28]:
stats.norm.stats(loc=3, scale=4, moments="mv")

(array(3.), array(16.))

In [33]:
x = stats.norm.rvs(size=10)
x

array([-0.52192681,  1.75559828,  2.42274174, -1.68325625, -0.72179758,
        0.5009768 ,  0.527632  ,  1.54650398, -0.76484794, -0.38386071])