In [ ]:
"""

# F Test in R

> boy <-  c(46,47,58,47,27,58,56,26,47,25)
> girl <- c(78,57,31,28,67,77,36,57,36,57)
> var.test(boy,girl)

	F test to compare two variances

data:  boy and girl
F = 0.4923, num df = 9, denom df = 9, p-value = 0.306
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.1222795 1.9819824
sample estimates:
ratio of variances 
         0.4922964 

> var.test(girl,boy)

	F test to compare two variances

data:  girl and boy
F = 2.0313, num df = 9, denom df = 9, p-value = 0.306
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.5045454 8.1779885
sample estimates:
ratio of variances 
          2.031297 
"""

In [31]:
import numpy as np
import pandas as pd
import scipy

In [17]:
boy  = [46,47,58,47,27,58,56,26,47,25]


In [3]:
girl = [78,57,31,28,67,77,36,57,36,57]


In [7]:
np.var(boy, ddof=1)

171.1222222222222

In [8]:
np.var(girl, ddof=1)

347.59999999999997

In [10]:
np.var(boy, ddof=1)/np.var(girl, ddof=1)

0.4922963815368879

In [12]:
np.var(girl, ddof=1)/ np.var(boy, ddof=1)

2.0312966690474643

In [13]:
from sklearn.feature_selection import f_regression

In [23]:
b  = np.array(boy)
g = np.array(girl)

In [22]:
b

array([46, 47, 58, 47, 27, 58, 56, 26, 47, 25])

In [29]:
f_regression(b.reshape(-1, 1), g.reshape(-1, 1))

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


(array([0.71273115]), array([0.42306411]))

In [28]:
b.reshape(-1, 1)

array([[46],
       [47],
       [58],
       [47],
       [27],
       [58],
       [56],
       [26],
       [47],
       [25]])

In [40]:
scipy.stats.f.cdf(np.var(boy, ddof=1)/ np.var(girl, ddof=1) , 9,9)

0.15298112821065285

In [39]:
np.var(boy, ddof=1)/ np.var(girl, ddof=1)

0.4922963815368879

In [44]:
scipy.stats.f.cdf(9999,10,10)

0.9999999999999999

In [49]:
import scipy.stats as stats

stats.f_oneway(boy,girl)

F_onewayResult(statistic=1.4591624718860445, pvalue=0.24269553293319618)

In [48]:

fstatistics = np.var(boy, ddof=1)/np.var(girl, ddof=1)
fdistribution = stats.f(len(boy)-1,len(girl)-1)
p_value = 2*min(fdistribution.cdf(fstatistics ), 1-fdistribution.cdf(fstatistics )) # two tailed test
p_value


0.3059622564213057

In [50]:
f_critical1 = fdistribution.ppf(0.025)
f_critical2 = fdistribution.ppf(0.975)
print(fstatistics,f_critical1, f_critical2 )
if (p_value<0.05):
    print('Reject H0', p_value)
else:
    print('Cant Reject H0', p_value)

0.4922963815368879 0.24838585469445493 4.025994158282978
Cant Reject H0 0.3059622564213057


In [52]:
stats.f(boy.girl)

AttributeError: 'list' object has no attribute 'girl'

In [62]:
scipy.stats.f.cdf(fstatistics, 9, 9)

0.15298112821065285

In [63]:
def f_test(x, y):
    x = np.array(x)
    y = np.array(y)
    f = np.var(x, ddof=1)/np.var(y, ddof=1) #calculate F test statistic 
    dfn = x.size-1 #define degrees of freedom numerator 
    dfd = y.size-1 #define degrees of freedom denominator 
    p = 1-scipy.stats.f.cdf(f, dfn, dfd) #find p-value of F test statistic 
    return f, p


In [65]:
f_test(girl,boy)

(2.0312966690474643, 0.1529811282106528)

In [ ]:
import statistics as stats
import scipy.stats as ss
def Ftest_pvalue(d1,d2):
    """docstring for Ftest_pvalue"""
    df1 = len(d1) - 1
    df2 = len(d2) - 1
    F = stats.variance(d1) / stats.variance(d2)
    single_tailed_pval = ss.f.cdf(F,df1,df2)
    double_tailed_pval = single_tailed_pval * 2
    return double_tailed_pval
