In [1]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[4,5,6]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [6]:
x.mean(axis=1)

array([2., 5.])

AxisError: axis 2 is out of bounds for array of dimension 2