In [ ]:
# 출력을 원하실 경우 print() 활용
# 예) print(df.head())

# 답안 제출 예시
# 수험번호.csv 생성
# DataFrame.to_csv("0000.csv", index=False)

In [1]:
import pandas as pd
import numpy as np

In [8]:
X_train = pd.read_csv("X_train.csv", encoding="cp949")
y_train = pd.read_csv("y_train.csv", encoding="cp949")
X_test = pd.read_csv("X_test.csv", encoding="cp949")

In [9]:
X_train.head()

cust_id      총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0        0  68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1        1   2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2        2   3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3        3  16077620   4935000        NaN      기타   광주점    18  2.444444   
4        4  29050000  24000000        NaN      보석  본  점     2  1.500000   

     주말방문비율  구매주기  
0  0.527027    17  
1  0.000000     1  
2  0.000000     1  
3  0.318182    16  
4  0.000000    85

주구매상품_가공식품  주구매상품_가구  주구매상품_건강식품  주구매상품_골프  주구매상품_구두  주구매상품_기타  \
0              0         0           0         0         0         1   
1              0         0           0         0         0         0   
2              0         0           0         0         0         0   
3              0         0           0         0         0         1   
4              0         0           0         0         0         0   
...          ...       ...         ...       ...       ...       ...   
3495           0         0           0         1         0         0   
3496           0         0           0         0         0         0   
3497           0         0           0         0         0         0   
3498           0         0           0         0         0         0   
3499           0         0           0         0         0         1   

      주구매상품_남성 캐주얼  주구매상품_남성 트랜디  주구매상품_남성정장  주구매상품_농산물  ...  주구매상품_주방용품  \
0                0             0           0          0  ...           0   
1                0             0           0          0  ...           0   
2                1             0           0          0  ...           0   
3                0             0           0          0  ...           0   
4                0             0           0          0  ...           0   
...            ...           ...         ...        ...  ...         ...   
3495             0             0           0          0  ...           0   
3496             0             0           0          0  ...           0   
3497             0             0           0          0  ...           1   
3498             0             0           0          0  ...           0   
3499             0             0           0          0  ...           0   

      주구매상품_차/커피  주구매상품_축산가공  주구매상품_침구/수예  주구매상품_캐주얼  주구매상품_커리어  주구매상품_통신/컴퓨터  \
0              0           0            0          0          0             0   
1              0           0            0          0          0             0   
2              0           0            0          0          0             0   
3              0           0            0          0          0             0   
4              0           0            0          0          0             0   
...          ...         ...          ...        ...        ...           ...   
3495           0           0            0          0          0             0   
3496           0           0            0          0          0             0   
3497           0           0            0          0          0             0   
3498           0           0            0          0          0             0   
3499           0           0            0          0          0             0   

      주구매상품_트래디셔널  주구매상품_피혁잡화  주구매상품_화장품  
0               0           0          0  
1               0           0          0  
2               0           0          0  
3               0           0          0  
4               0           0          0  
...           ...         ...        ...  
3495            0           0          0  
3496            0           0          0  
3497            0           0          0  
3498            0           0          1  
3499            0           0          0  

[3500 rows x 42 columns]

In [10]:
y_train.head()

cust_id  gender
0        0       0
1        1       0
2        2       1
3        3       1
4        4       0

In [11]:
X_test.head()

cust_id       총구매액     최대구매액        환불금액 주구매상품 주구매지점  내점일수    내점당구매건수  \
0     3500   70900400  22000000   4050000.0    골프  부산본점    13   1.461538   
1     3501  310533100  38558000  48034700.0   농산물   잠실점    90   2.433333   
2     3502  305264140  14825000  30521000.0  가공식품  본  점   101  14.623762   
3     3503    7594080   5225000         NaN  주방용품  부산본점     5   2.000000   
4     3504    1795790   1411200         NaN   수산품  청량리점     3   2.666667   

     주말방문비율  구매주기  
0  0.789474    26  
1  0.369863     3  
2  0.083277     3  
3  0.000000    47  
4  0.125000     8

In [57]:
from sklearn.model_selection import cross_val_predict, cross_val_score

In [13]:
from sklearn.linear_model import LogisticRegression

In [100]:
logiesti = LogisticRegression(C=10000)

In [21]:
X= X_train[['총구매액','최대구매액','환불금액', '내점일수','내점당구매건수','주말방문비율','구매주기']]

In [28]:
X2 = X.fillna(0)

In [29]:
X2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   총구매액     3500 non-null   int64  
 1   최대구매액    3500 non-null   int64  
 2   환불금액     3500 non-null   float64
 3   내점일수     3500 non-null   int64  
 4   내점당구매건수  3500 non-null   float64
 5   주말방문비율   3500 non-null   float64
 6   구매주기     3500 non-null   int64  
dtypes: float64(3), int64(4)
memory usage: 191.5 KB


In [94]:
X3= X_train[['최대구매액','구매주기','내점일수']]

In [77]:
X3.shape, y_train.gender.shape

((3500, 2), (3500,))

In [103]:
predic = cross_val_predict(logiesti, X3, y_train.gender,  verbose=3, cv=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished


In [89]:
predic, predic.shape, predic.max(), predic.min()

(array([0, 0, 0, ..., 0, 0, 0]), (3500,), 1, 0)

In [104]:
pd.DataFrame({'true':y_train.gender, 'pred':predic})

true  pred
0        0     0
1        0     0
2        1     0
3        1     0
4        0     0
...    ...   ...
3495     1     0
3496     1     0
3497     0     0
3498     0     0
3499     0     0

[3500 rows x 2 columns]

In [105]:
pd.DataFrame({'true':y_train.gender, 'pred':predic}).value_counts()

true  pred
0     0       2183
1     0       1316
0     1          1
dtype: int64

In [116]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [98]:
precision_score(y_train.gender, predic)

0.0

In [99]:
recall_score(y_train.gender, predic)

0.0

In [41]:
y_train[['gender']].value_counts()

gender
0         2184
1         1316
dtype: int64

In [43]:
pd.DataFrame(predic).value_counts()

0    3500
dtype: int64

In [61]:
pd.DataFrame(predic).describe()

0
count  5.000000
mean   0.624000
std    0.000639
min    0.622857
25%    0.624286
50%    0.624286
75%    0.624286
max    0.624286

In [67]:
pd.concat([X_train, y_train[['gender']]], axis = 1)

cust_id       총구매액     최대구매액       환불금액   주구매상품 주구매지점  내점일수   내점당구매건수  \
0           0   68282840  11264000  6860000.0      기타   강남점    19  3.894737   
1           1    2136000   2136000   300000.0     스포츠   잠실점     2  1.500000   
2           2    3197000   1639000        NaN  남성 캐주얼   관악점     2  2.000000   
3           3   16077620   4935000        NaN      기타   광주점    18  2.444444   
4           4   29050000  24000000        NaN      보석  본  점     2  1.500000   
...       ...        ...       ...        ...     ...   ...   ...       ...   
3495     3495    3175200   3042900        NaN      골프  본  점     1  2.000000   
3496     3496   29628600   7200000  6049600.0    시티웨어  부산본점     8  1.625000   
3497     3497      75000     75000        NaN    주방용품   창원점     1  1.000000   
3498     3498    1875000   1000000        NaN     화장품  본  점     2  1.000000   
3499     3499  263101550  34632000  5973000.0      기타  본  점    38  2.421053   

        주말방문비율  구매주기  gender  
0     0.527027    17       0  
1     0.000000     1       0  
2     0.000000     1       1  
3     0.318182    16       1  
4     0.000000    85       0  
...        ...   ...     ...  
3495  1.000000     0       1  
3496  0.461538    40       1  
3497  0.000000     0       0  
3498  0.000000    39       0  
3499  0.467391     8       0  

[3500 rows x 11 columns]

In [69]:
pd.concat([X_train, y_train[['gender']]], axis = 1).corr()

cust_id      총구매액     최대구매액      환불금액      내점일수   내점당구매건수    주말방문비율  \
cust_id  1.000000 -0.008004 -0.005883  0.070135 -0.025234 -0.004840  0.001900   
총구매액    -0.008004  1.000000  0.700080  0.419734  0.659084  0.090022  0.014396   
최대구매액   -0.005883  0.700080  1.000000  0.410562  0.374147  0.018980  0.022277   
환불금액     0.070135  0.419734  0.410562  1.000000  0.270290 -0.063114 -0.062397   
내점일수    -0.025234  0.659084  0.374147  0.270290  1.000000  0.225264 -0.010325   
내점당구매건수 -0.004840  0.090022  0.018980 -0.063114  0.225264  1.000000  0.007659   
주말방문비율   0.001900  0.014396  0.022277 -0.062397 -0.010325  0.007659  1.000000   
구매주기     0.020070 -0.212944 -0.115837 -0.211125 -0.293200 -0.091151  0.003372   
gender  -0.001994 -0.150141 -0.114323 -0.078025 -0.155000 -0.043917  0.073598   

             구매주기    gender  
cust_id  0.020070 -0.001994  
총구매액    -0.212944 -0.150141  
최대구매액   -0.115837 -0.114323  
환불금액    -0.211125 -0.078025  
내점일수    -0.293200 -0.155000  
내점당구매건수 -0.091151 -0.043917  
주말방문비율   0.003372  0.073598  
구매주기     1.000000  0.041450  
gender   0.041450  1.000000

In [107]:
from sklearn.ensemble import RandomForestClassifier

In [108]:
rfc = RandomForestClassifier()

In [109]:
predic = cross_val_predict(rfc, X3, y_train.gender,  verbose=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.9s finished


In [126]:
pred_proba = cross_val_predict(rfc, X3, y_train.gender,  verbose=3, method='predict_proba')

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.9s finished


In [128]:
pd.concat([y_train.gender, predic], axis=0)

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid

In [130]:
pd.DataFrame({'true':y_train.gender, 'pred':pred_proba})

Exception: Data must be 1-dimensional

In [131]:
pred_proba

array([[0.93, 0.07],
       [0.16, 0.84],
       [0.43, 0.57],
       ...,
       [0.07, 0.93],
       [0.75, 0.25],
       [0.98, 0.02]])

In [113]:
pd.DataFrame({'true':y_train.gender, 'pred':predic}).value_counts()

true  pred
0     0       1600
1     0        864
0     1        584
1     1        452
dtype: int64

In [114]:
precision_score(y_train.gender, predic)

0.4362934362934363

In [115]:
recall_score(y_train.gender, predic)

0.3434650455927052

In [117]:
f1_score(y_train.gender, predic)

0.3843537414965987

In [118]:
predic = cross_val_predict(logiesti, X_train, y_train.gender,  verbose=3, cv=3)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


ValueError: could not convert string to float: '골프'

In [119]:
from sklearn.preprocessing import OneHotEncoder

In [120]:
onehot = OneHotEncoder()

In [122]:
X1 = X_train.fillna(0)

In [123]:
onehot.fit(X1)

OneHotEncoder()

In [124]:
onehot.categories_

[array([   0,    1,    2, ..., 3497, 3498, 3499]),
 array([ -52421520,  -18905600,   -2992000, ..., 1624088220, 1715219490,
        2323180070]),
 array([ -2992000,      5000,      5500, ..., 382096000, 391000000,
        706629000]),
 array([0.0000000e+00, 5.6000000e+03, 1.8000000e+04, ..., 3.8152100e+08,
        5.2960232e+08, 5.6375300e+08]),
 array(['가공식품', '가구', '건강식품', '골프', '구두', '기타', '남성 캐주얼', '남성 트랜디', '남성정장',
        '농산물', '대형가전', '디자이너', '란제리/내의', '명품', '모피/피혁', '보석', '생활잡화',
        '섬유잡화', '셔츠', '소형가전', '수산품', '스포츠', '시티웨어', '식기', '아동', '악기',
        '액세서리', '육류', '일용잡화', '젓갈/반찬', '주류', '주방가전', '주방용품', '차/커피',
        '축산가공', '침구/수예', '캐주얼', '커리어', '통신/컴퓨터', '트래디셔널', '피혁잡화', '화장품'],
       dtype=object),
 array(['강남점', '관악점', '광주점', '노원점', '대구점', '대전점', '동래점', '미아점', '본  점',
        '부산본점', '부평점', '분당점', '상인점', '센텀시티점', '안양점', '영등포점', '울산점', '인천점',
        '일산점', '잠실점', '전주점', '창원점', '청량리점', '포항점'], dtype=object),
 array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,