In [1]:
# https://blog.naver.com/ostin1038/222123922113

In [2]:
import pandas as pd
import numpy as np

In [3]:
D = pd.read_csv('data/electronic_music.csv')
D.head()

ZCRm   Energym  EnergyEntropym  SpectralCentroidm  SpectralEntropym  \
0  0.136440  0.088861        3.201201           0.262825          1.114423   
1  0.117039  0.108389        3.194001           0.247657          1.065668   
2  0.085308  0.128525        3.123837           0.217205          0.789647   
3  0.103050  0.167042        3.150830           0.233593          0.967082   
4  0.151730  0.148405        3.194498           0.293730          1.353005   

     MFCCs1m   MFCCs2m  ChromaVector1m  ChromaDeviationm  EnergyEntropystd  \
0 -22.723259  1.594074        0.011581          0.032185          0.102995   
1 -21.775871  1.261364        0.006535          0.041116          0.099449   
2 -22.472722  1.425185        0.007143          0.066049          0.117704   
3 -21.470751  1.463686        0.010724          0.046159          0.134908   
4 -21.371157  1.187854        0.009624          0.036761          0.122271   

   SpectralCentroidstd  SpectralSpreadstd  SpectralEntropystd  \
0             0.041285           0.017725            0.414831   
1             0.039386           0.018946            0.407164   
2             0.041509           0.022645            0.340130   
3             0.032564           0.020036            0.365068   
4             0.036637           0.017732            0.458740   

   SpectralFluxstd  SpectralRolloffstd  MFCCs1std  ChromaVector1std  BPM  \
0         0.005867            0.133778   0.838302          0.013138  128   
1         0.003613            0.110334   0.624185          0.006761  126   
2         0.007697            0.085784   1.028740          0.007836  129   
3         0.005215            0.086336   0.769981          0.008330  129   
4         0.002900            0.148464   1.023154          0.010860  129   

     class  
0  BigRoom  
1  BigRoom  
2  BigRoom  
3  BigRoom  
4  BigRoom

In [6]:
# 전처리: 왜도가 2 혹은 첨도가 3 이상인 변수는 log함수를 활용해 값을 전환하고 ex) log( A)
# 이전 변수는 제거하시오. 그리고 해당 데이터셋을 Base table로 지정하고 문제풀기를 진행하시오.

In [4]:
D.agg(['skew','kurtosis']).T

skew   kurtosis
ZCRm                 0.201446  -0.102927
Energym              0.670077   0.683374
EnergyEntropym      -0.652767   0.717547
SpectralCentroidm   -0.229501  -0.142066
SpectralEntropym     0.012365  -0.535248
MFCCs1m             -0.600440   0.922292
MFCCs2m              0.433142   0.265782
ChromaVector1m       2.417819  10.554305
ChromaDeviationm     0.732361   1.128118
EnergyEntropystd     0.853229   0.983863
SpectralCentroidstd  0.558354   0.112850
SpectralSpreadstd    0.371599  -0.080602
SpectralEntropystd   0.350614   0.217055
SpectralFluxstd      1.858985   7.687473
SpectralRolloffstd   0.239307  -0.099013
MFCCs1std            0.891322   2.897663
ChromaVector1std     1.912441   6.232342
BPM                 -0.976322   1.007368

In [5]:
D.apply(['skew', 'kurtosis'], axis=0)

ZCRm   Energym  EnergyEntropym  SpectralCentroidm  \
skew      0.201446  0.670077       -0.652767          -0.229501   
kurtosis -0.102927  0.683374        0.717547          -0.142066   

          SpectralEntropym   MFCCs1m   MFCCs2m  ChromaVector1m  \
skew              0.012365 -0.600440  0.433142        2.417819   
kurtosis         -0.535248  0.922292  0.265782       10.554305   

          ChromaDeviationm  EnergyEntropystd  SpectralCentroidstd  \
skew              0.732361          0.853229             0.558354   
kurtosis          1.128118          0.983863             0.112850   

          SpectralSpreadstd  SpectralEntropystd  SpectralFluxstd  \
skew               0.371599            0.350614         1.858985   
kurtosis          -0.080602            0.217055         7.687473   

          SpectralRolloffstd  MFCCs1std  ChromaVector1std       BPM  
skew                0.239307   0.891322          1.912441 -0.976322  
kurtosis           -0.099013   2.897663          6.232342  1.007368

In [6]:
# log 변환
D['ChromaVector1m_log'] = np.log(D.ChromaVector1m)
D['SpectralFluxstd_log'] = np.log(D.SpectralFluxstd)
D['ChromaVector1std_log'] = D.ChromaVector1std.map( lambda x: np.log(x)) # 이 방법도 동일함

In [7]:
B = D.drop(['ChromaVector1m','SpectralFluxstd','ChromaVector1std'], axis=1)
B.head()

ZCRm   Energym  EnergyEntropym  SpectralCentroidm  SpectralEntropym  \
0  0.136440  0.088861        3.201201           0.262825          1.114423   
1  0.117039  0.108389        3.194001           0.247657          1.065668   
2  0.085308  0.128525        3.123837           0.217205          0.789647   
3  0.103050  0.167042        3.150830           0.233593          0.967082   
4  0.151730  0.148405        3.194498           0.293730          1.353005   

     MFCCs1m   MFCCs2m  ChromaDeviationm  EnergyEntropystd  \
0 -22.723259  1.594074          0.032185          0.102995   
1 -21.775871  1.261364          0.041116          0.099449   
2 -22.472722  1.425185          0.066049          0.117704   
3 -21.470751  1.463686          0.046159          0.134908   
4 -21.371157  1.187854          0.036761          0.122271   

   SpectralCentroidstd  SpectralSpreadstd  SpectralEntropystd  \
0             0.041285           0.017725            0.414831   
1             0.039386           0.018946            0.407164   
2             0.041509           0.022645            0.340130   
3             0.032564           0.020036            0.365068   
4             0.036637           0.017732            0.458740   

   SpectralRolloffstd  MFCCs1std  BPM    class  ChromaVector1m_log  \
0            0.133778   0.838302  128  BigRoom           -4.458414   
1            0.110334   0.624185  126  BigRoom           -5.030514   
2            0.085784   1.028740  129  BigRoom           -4.941600   
3            0.086336   0.769981  129  BigRoom           -4.535317   
4            0.148464   1.023154  129  BigRoom           -4.643453   

   SpectralFluxstd_log  ChromaVector1std_log  
0            -5.138444             -4.332284  
1            -5.623269             -4.996584  
2            -4.866961             -4.849030  
3            -5.256150             -4.787846  
4            -5.842930             -4.522707

In [8]:
# Q1
_ = """
Q1: 먼저 18개 변수를 차원 축소를 통해 변수의 수를 줄이고자 한다. 
    주성분분석 PCA를 진행하고자 하는데 이를 위해 표준화를 진행한다. 
    이때 표준화는 standardscaler 방식으로 따른다. 
    다음 표준화를 진행한 변수를 바탕으로 PCA 분석을 수행한다. 
    (SVD solver:auto, Seed:13, 나머지 디폴트) 
    이때 다섯번째 주성분의 누적 분산 비율을 구하시오.
    (소수 셋째자리 버림 둘째자리 구하시오) 
"""

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [10]:
scaler = StandardScaler()

In [11]:
pca = PCA(n_components=5, svd_solver="auto", random_state=13)

In [12]:
from sklearn.pipeline import Pipeline

In [13]:
pipe = Pipeline([('scaler', scaler),
                 ('pca', pca)])

In [15]:
pipe.fit(B.drop('class', axis=1))

Pipeline(steps=[('scaler', StandardScaler()),
                ('pca', PCA(n_components=5, random_state=13))])

In [16]:
pca.components_

array([[-2.87272750e-01, -1.07008401e-01, -3.13582010e-01,
        -2.73614367e-01, -3.19481377e-01, -3.10664625e-01,
         3.02475086e-01,  1.81663491e-01,  2.54525428e-01,
         2.28143524e-01,  3.40950740e-01, -1.10290297e-02,
        -1.52879134e-02,  2.71051956e-01, -3.13966020e-02,
        -1.55188588e-02,  3.17601427e-01,  2.73782862e-02],
       [ 3.02762378e-01, -7.42748656e-02, -1.61048590e-01,
         2.98077123e-01,  2.53562362e-01, -8.61501058e-02,
        -1.71722117e-01, -1.22231655e-01,  2.71517448e-01,
         3.29248864e-01,  2.59375416e-02,  4.57672256e-01,
         4.45082214e-01,  2.58400426e-01, -7.01916870e-02,
        -6.43647596e-03,  7.26633567e-02,  6.71295841e-02],
       [-2.16297024e-02,  3.50349512e-01, -1.43327143e-04,
         1.03701446e-01, -1.26890162e-02,  6.09887127e-02,
        -1.42442203e-01,  4.10563419e-01, -7.72349126e-02,
         7.53547802e-02, -2.21695976e-02,  3.76388863e-02,
         5.49911527e-02,  5.57980333e-02,  1.97466499e

In [17]:
pca.get_covariance()

array([[ 1.10523582,  0.01977845,  0.35536031,  0.85335826,  0.90485077,
         0.41879261, -0.76227577, -0.52670659, -0.11116523, -0.03297061,
        -0.59515211,  0.56451383,  0.55219628, -0.17957283,  0.01433481,
         0.01696736, -0.51134812,  0.01745587],
       [ 0.01977845,  0.94667856,  0.35137579,  0.20111238,  0.05933091,
         0.50230929, -0.20589514,  0.37823875, -0.4044909 , -0.08066219,
        -0.20361965, -0.02588444,  0.02564171, -0.2238788 , -0.00838532,
        -0.26790223, -0.01197235, -0.24118994],
       [ 0.35536031,  0.35137579,  0.94913646,  0.35376854,  0.45088956,
         0.72397602, -0.47504689, -0.24526937, -0.70298944, -0.64258748,
        -0.68180729, -0.25764422, -0.23532838, -0.70614011,  0.05698842,
         0.07927345, -0.65479789, -0.04122411],
       [ 0.85335826,  0.20111238,  0.35376854,  1.0572036 ,  0.85149837,
         0.46209821, -0.75985455, -0.35738441, -0.13744262,  0.02721641,
        -0.56063086,  0.5834007 ,  0.58230692, -0.145

In [18]:
pca.explained_variance_

array([6.52586066, 4.23793035, 2.48029822, 1.20867554, 0.97488583])

In [19]:
pca.explained_variance_ratio_

array([0.36239018, 0.23533821, 0.13773444, 0.06711945, 0.05413678])

In [20]:
np.sum(pca.explained_variance_ratio_[0:5])

0.8567190510961913

In [30]:
# Q2 
_ = """
Q2: 23개 장르를 보다 압축하기 위해 계층적 군집(Hierarchical clustering) 모형을 수행하고자 한다. 
    군집 간거리계산 방법은 유클리드 거리를 기록하고 병합은 와드 연결법으로 진행한다.
    (나머지 디폴트) 
    이때 변수는 Q1을 통해 수행한 0부터 4까지 다섯개까지 합성변수를 바탕으로 하고 군집간 거리를 통해 3개의 군집으로 나누어 본다. 
    이때 한 군집으로의 쏠림현상이 가장 큰 장르는 무엇인지 서술하시오.
"""

In [21]:
principals = pipe.transform(B.drop('class', axis=1))

In [22]:
pd.DataFrame(data=principals)

0         1         2         3         4
0    -2.572629 -0.456240 -1.400974 -0.264937 -0.298986
1    -2.989018 -1.382327  0.471413 -0.538964  0.103854
2    -0.436349 -2.147236  1.335692  0.287323 -0.243133
3    -2.167112 -1.980958  0.270651  0.758668 -0.506565
4    -3.989842  0.204576 -0.209533  0.434385 -0.428017
...        ...       ...       ...       ...       ...
2295 -3.535457 -1.944560 -0.510565 -1.415858 -0.262645
2296 -1.802725 -0.352227 -1.516525 -0.469097 -1.163776
2297 -2.870869 -2.756903 -0.960233 -2.092609  2.865507
2298 -2.490432 -1.344074  1.970601 -1.272466 -0.114503
2299 -4.658586 -1.470133 -1.535060 -1.900394 -0.305054

[2300 rows x 5 columns]

In [23]:
from sklearn.cluster import AgglomerativeClustering

In [24]:
aggcluster = AgglomerativeClustering(n_clusters=3, linkage="ward", affinity="euclidean")

In [25]:
aggcluster.fit(principals)

AgglomerativeClustering(n_clusters=3)

In [26]:
aggcluster.labels_

array([2, 2, 1, ..., 2, 2, 2])

In [27]:
pd.crosstab(aggcluster.labels_, B['class'], margins=True)

class  BigRoom  Breaks  Dance  DeepHouse  DrumAndBass  Dubstep  ElectroHouse  \
row_0                                                                          
0           11      60     59         27           59       37            35   
1            5      23     17         72            8        6             6   
2           84      17     24          1           33       57            59   
All        100     100    100        100          100      100           100   

class  ElectronicaDowntempo  FunkRAndB  FutureHouse  ...  House  \
row_0                                                ...          
0                        23         79           50  ...     75   
1                        74         18           12  ...     15   
2                         3          3           38  ...     10   
All                     100        100          100  ...    100   

class  IndieDanceNuDisco  Minimal  ProgressiveHouse  PsyTrance  ReggaeDub  \
row_0                                                                       
0                     55       22                19         19         63   
1                     45       78                74         67         31   
2                      0        0                 7         14          6   
All                  100      100               100        100        100   

class  TechHouse  Techno  Trance   All  
row_0                                   
0             68      36      10   958  
1             32      60       5   742  
2              0       4      85   600  
All          100     100     100  2300  

[4 rows x 24 columns]

In [29]:
pd.crosstab(aggcluster.labels_, B['class'], margins=True).T

row_0                   0    1    2   All
class                                    
BigRoom                11    5   84   100
Breaks                 60   23   17   100
Dance                  59   17   24   100
DeepHouse              27   72    1   100
DrumAndBass            59    8   33   100
Dubstep                37    6   57   100
ElectroHouse           35    6   59   100
ElectronicaDowntempo   23   74    3   100
FunkRAndB              79   18    3   100
FutureHouse            50   12   38   100
GlitchHop              73   17   10   100
HardDance              10    5   85   100
HardcoreHardTechno     22   63   15   100
HipHop                 46    9   45   100
House                  75   15   10   100
IndieDanceNuDisco      55   45    0   100
Minimal                22   78    0   100
ProgressiveHouse       19   74    7   100
PsyTrance              19   67   14   100
ReggaeDub              63   31    6   100
TechHouse              68   32    0   100
Techno                 36   60    4   100
Trance                 10    5   85   100
All                   958  742  600  2300

In [31]:
# Q3
_ = """
Q3: Q1-Q2를 종합적으로 KNN 분류 예측 모형을 만들고자 한다. 
먼저 Q2에서 군집분석 수행한 결과를 바탕으로 
데이터 분할을 트레인셋: 테스트셋 7:3 비율로 진행한다.(Seed:13)
다음 독립변수로는 앞서진행한 다섯개 주성분 합성변수로 진행하고 
종속변수는 3개의 클러스터 값으로 구분된 군집정보가 들어있는 변수를 지정한다.
이때 number of neighbors K값은 9로 지정하고 거리측정 방식은 맨하탄 거리측정으로 진행한다.
이후 KNN분류 예측 모형 평가를 진행하고자 한다. 
테스트 셋 690개에 대해 House 장르가 많은 비중을 차지했던 클러스터 집단에 해당하는 라벨값 Precision을 구하시오
(소수 셋째자리 버림 둘째자리 구하시오) 
"""

In [33]:
# house 는 클러스터 0
pd.DataFrame({'cluster':aggcluster.labels_}).head()

cluster
0        2
1        2
2        1
3        2
4        2

In [32]:
pd.DataFrame(data=principals, columns=["pca1","pca2","pca3","pca4","pca5",]).head()

pca1      pca2      pca3      pca4      pca5
0 -2.572629 -0.456240 -1.400974 -0.264937 -0.298986
1 -2.989018 -1.382327  0.471413 -0.538964  0.103854
2 -0.436349 -2.147236  1.335692  0.287323 -0.243133
3 -2.167112 -1.980958  0.270651  0.758668 -0.506565
4 -3.989842  0.204576 -0.209533  0.434385 -0.428017

In [37]:
X = pd.DataFrame(data=principals, columns=["pca1","pca2","pca3","pca4","pca5",])
y = aggcluster.labels_

In [45]:
X.shape, y.shape

((2300, 5), (2300,))

In [54]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size = 0.3,random_state = 13)

In [55]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1610, 5), (690, 5), (1610,), (690,))

In [56]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=9, p=1)

In [58]:
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9, p=1)

In [59]:
prediction = model.predict(X_test)

In [67]:
pd.DataFrame({"true":y_test, "predict": prediction}).head()

true  predict
0     1        1
1     1        1
2     2        0
3     2        2
4     1        0

In [64]:
from sklearn.metrics import recall_score, precision_score

In [68]:
precision_score(y_test == 0, prediction == 0)

0.9377049180327869

In [69]:
recall_score(y_test == 0, prediction == 0)

0.9470198675496688

In [71]:
pd.crosstab(y_test, prediction)

col_0    0    1    2
row_0               
0      286    6   10
1       13  188    0
2        6    1  180